run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - goconst
  - gocritic
  - goimports
  - gosimple
  - govet
  - ineffassign
  - prealloc
  - staticcheck
  - structcheck
  - stylecheck
  - unparam
  - unused
  - varcheck

linters-settings:
  goimports:
    local-prefixes: coreos/ignition
