name: Go
# Trigger the CI on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:

  test-build:
    name: Verify test build
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install libblkid-dev
      run: sudo apt-get install libblkid-dev
    - name: Test container build
      run: |
        ./test
        docker build -f Dockerfile.validate .
  linting:
    name: Lint
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install libblkid-dev
        run: sudo apt-get install libblkid-dev
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          args: -E=gofmt --timeout=30m0s
